In [1]:
import numpy as np

In [2]:
arr =  np.array([1,2,3])

In [3]:
arr

array([1, 2, 3])

In [4]:
# array of zero
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
#array of one's
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
np.full((4,6),8)

array([[8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8]])

In [7]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
np.arange(1,100,9)#1+9+9.....n-1 limit

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [10]:
np.arange(1,100,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [11]:
np.linspace(0,1,5)#0 to 1 divided in 5 steps equaly

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [12]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [14]:
myarr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [15]:
myarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [16]:
myarr.shape


(4, 3)

In [17]:
myarr.size

12

In [18]:
myarr.ndim

2

In [19]:
myarr.dtype

dtype('int64')

In [22]:
myarr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]],dtype='float32')#converting all array to float

In [23]:
myarr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]], dtype=float32)

In [25]:
#converting data type
n = myarr.astype('float64')


In [26]:
n.dtype

dtype('float64')

In [27]:
myarr.dtype

dtype('float32')

In [28]:
myarr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [29]:
myarr.shape

(4, 3)

In [30]:
reshape = myarr.reshape((3,4))

In [31]:
reshape

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [32]:
myarr.reshape((2,6))

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])