In [3]:
import numpy as np

In [4]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [5]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [6]:
#making the array flat and then performing all function over it
flat = arr.flatten()

In [7]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [8]:
flat[0]

np.int64(1)

In [9]:
flat[3:6]#from index 3 to 5

array([4, 5, 6])

In [10]:
 flat[:5]# will print till index 4

array([1, 2, 3, 4, 5])

In [11]:
flat[3:]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])

In [12]:
b = flat[3:7]#here b is not a copy it is a view

In [13]:
b

array([4, 5, 6, 7])

In [14]:
b[0]=4444#here not only it will change in b but it will also change in arr as the value at that memory is changing

In [15]:
flat

array([   1,    2,    3, 4444,    5,    6,    7,    8,    9,   10,   11,
         12])

In [16]:
# as if we slicw=e n use it will change in both arr so to avoid that we use copy
b=flat[3:7].copy()

In [17]:
b

array([4444,    5,    6,    7])

In [18]:
b[0]=111111

In [19]:
b

array([111111,      5,      6,      7])

In [20]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [21]:
flat

array([   1,    2,    3, 4444,    5,    6,    7,    8,    9,   10,   11,
         12])

In [22]:
#fancy Indexing

arr=np.array([1,34,43,56,23,14,67,36,74,22,67])


In [23]:
arr[[1,4,6]]

array([34, 23, 67])

In [24]:
#boolean masking
arr[arr>34]


array([43, 56, 67, 36, 74, 67])