In [1]:
import numpy as np

In [2]:
arr=np.array([3,5,2,33])

In [3]:
np.mean(arr)

np.float64(10.75)

In [4]:
np.std(arr)

np.float64(12.891373084353738)

In [5]:
np.var(arr)

np.float64(166.1875)

In [6]:
np.min(arr)

np.int64(2)

In [7]:
np.max(arr)

np.int64(33)

In [8]:
np.sum(arr)

np.int64(43)

In [9]:
np.prod(arr)

np.int64(990)

In [10]:
np.median(arr)

np.float64(4.0)

In [11]:
np.percentile(arr, 50)  # For the 50th percentile (median)

np.float64(4.0)

In [12]:
np.argmin(arr)

np.int64(2)

In [13]:
np.argmax(arr)

np.int64(3)

In [15]:
arr1=([[1,2,3],[4,5,6]])
arr2=([[1,2,3],[7,8,9]])
np.corrcoef(arr1, arr2)


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
np.unique(arr)

array([ 2,  3,  5, 33])

In [17]:
np.diff(arr)

array([ 2, -3, 31])

In [18]:
np.cumsum(arr)

array([ 3,  8, 10, 43])

In [19]:
np.linspace(0, 10, 5)  # 5 numbers from 0 to 10

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [20]:
np.log(arr)

array([1.09861229, 1.60943791, 0.69314718, 3.49650756])

In [21]:
np.exp(arr)

array([2.00855369e+01, 1.48413159e+02, 7.38905610e+00, 2.14643580e+14])

In [23]:
np.argmin(arr)

np.int64(2)