In [1]:
import numpy as np

In [2]:
import time

In [6]:
#using python list
size = 1_000_000

l1 = list(range(size))
l2 = list(range(size))
start = time.time()
add = [x+y for x,y in zip(l1,l2)]
end = time.time()

print(end-start)

0.2921257019042969


In [7]:
#usingnumpy
#using python list
size = 1_000_000

l1 = np.array(list(range(size)))
l2 = np.array(list(range(size)))
start = time.time()
add = l1+l2
end = time.time()
print (add)
print(end-start)

[      0       2       4 ... 1999994 1999996 1999998]
0.07718229293823242


In [5]:
l1 = [1,2,4]
l2 = [6,7,8]
list(zip(l1,l2))


[(1, 6), (2, 7), (4, 8)]

In [8]:
arr = np.array([[1,2,3],[4,5,6]])

In [9]:
type(arr)

numpy.ndarray

In [10]:
arr.shape

(2, 3)

In [14]:
# vextorization of data 
# we can update or make changes in complete array whitout using any for loop 
arr_square = arr ** 2
print(arr_square)

[[ 1  4  9]
 [16 25 36]]


In [17]:
#with list withpou numpy
l=[1,2,3]
list_arr_square = [x ** 2 for x in l]
print(list_arr_square)

[1, 4, 9]
